name: Build LLVM/Clang

on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: 'LLVM version to build'
        required: true
        default: '21.1.1'
        type: string
      zlib_version:
        description: 'zlib version to build'
        required: true
        default: '1.3.1'
        type: string

permissions:
  # Required for uploading GitHub releases
  contents: write
  # Required for build provenance attestation
  id-token: write
  attestations: write

env:
  SCRIPTS_DIR: ${{ github.workspace }}/.github/workflows/llvm
  ZLIB_VERSION: ${{ github.event.inputs.zlib_version }}
  LLVM_VERSION: ${{ github.event.inputs.llvm_version }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.1
      
      - name: Install Dependencies
        run: $SCRIPTS_DIR/step-1_install_dependencies

      - name: Build zlib
        run: $SCRIPTS_DIR/step-2_build_zlib
      
      - name: Build LLVM
        run: $SCRIPTS_DIR/step-3_build_llvm
      
      - name: Package Toolchain
        run: $SCRIPTS_DIR/step-4_package_toolchain
      
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v3.0.0
        with:
          # This is ok: ARTIFACTS_DIR gets set by the environment script
          subject-path: ${{ env.ARTIFACTS_DIR }}/*.tar.xz
      
      - name: Upload Release
        run: $SCRIPTS_DIR/step-5_upload_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
