name: Build gcc standalone

on:
  workflow_dispatch:

permissions:
  # Required for uploading GitHub releases
  contents: write
  # Required for build provenance attestation
  id-token: write
  attestations: write

env:
  SCRIPTS_DIR: ${{ github.workspace }}/.github/workflows/build_gcc_standalone

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.0

      - name: Install Dependencies
        run: $SCRIPTS_DIR/step-01_install_dependencies

      - name: Download Source
        run: $SCRIPTS_DIR/step-02_download_source

      - name: Build ncurses
        run: $SCRIPTS_DIR/step-03_build_ncurses

      - name: Build zlib
        run: $SCRIPTS_DIR/step-04_build_zlib

      - name: Build zstd
        run: $SCRIPTS_DIR/step-05_build_zstd

      - name: Build GMP
        run: $SCRIPTS_DIR/step-06_build_gmp

      - name: Build MPFR
        run: $SCRIPTS_DIR/step-07_build_mpfr

      - name: Build ISL
        run: $SCRIPTS_DIR/step-08_build_isl

      - name: Build MPC
        run: $SCRIPTS_DIR/step-09_build_mpc

      - name: Build Expat
        run: $SCRIPTS_DIR/step-10_build_expat

      - name: Build Binutils
        run: $SCRIPTS_DIR/step-11_build_binutils

      - name: Install Linux Headers
        run: $SCRIPTS_DIR/step-12_install_linux_headers

      - name: Bootstrap GCC
        run: $SCRIPTS_DIR/step-13_bootstrap_gcc

      - name: Build glibc
        run: $SCRIPTS_DIR/step-14_build_glibc

      - name: Build GCC
        run: $SCRIPTS_DIR/step-15_build_gcc

      - name: Package Toolchain
        run: $SCRIPTS_DIR/step-16_package_toolchain

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v3.0.0
        with:
          subject-path: |
            ${{ env.ARTIFACTS_DIR }}/*.tar.xz

      - name: Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: $SCRIPTS_DIR/step-17_upload_release
