name: Build libclang

on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: 'LLVM version to build'
        required: true
        default: '21.1.1'
        type: string
      zlib_version:
        description: 'zlib version to build'
        required: true
        default: '1.3.1'
        type: string
      gcc_version:
        description: 'GCC version to use for compilation'
        required: true
        default: '15.2.0'
        type: string
      glibc_version:
        description: 'glibc version to link against'
        required: true
        default: '2.28'
        type: string

permissions:
  # Required for uploading GitHub releases
  contents: write
  # Required for build provenance attestation
  id-token: write
  attestations: write

env:
  SCRIPTS_DIR: ${{ github.workspace }}/.github/workflows/build_libclang
  UTILS_DIR: ${{ github.workspace }}/.github/workflows/utils
  ZLIB_VERSION: ${{ github.event.inputs.zlib_version }}
  LLVM_VERSION: ${{ github.event.inputs.llvm_version }}
  GCC_VERSION: ${{ github.event.inputs.gcc_version }}
  GLIBC_VERSION: ${{ github.event.inputs.glibc_version }}
  LINUX_VERSION: '6.18'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Install dependencies
        run: $SCRIPTS_DIR/step-1_install_dependencies

      - name: Set up environment
        run: $SCRIPTS_DIR/environment

      - name: Download zlib source
        run: $SCRIPTS_DIR/step-2.1_download_zlib_source
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Download LLVM source
        run: $SCRIPTS_DIR/step-2.2_download_llvm_source
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Install GCC toolchain
        run: $SCRIPTS_DIR/step-2.3_install_gcc
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Install Linux headers
        run: $SCRIPTS_DIR/step-2.4_install_linux_headers
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build zlib
        run: $SCRIPTS_DIR/step-3_build_zlib

      - name: Build libclang
        run: $SCRIPTS_DIR/step-4_build_libclang

      - name: Package toolchain
        run: $SCRIPTS_DIR/step-5_package_toolchain

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v4.1.0
        with:
          subject-path: |
            ${{ env.ARTIFACTS_DIR }}/*.tar.xz

      - name: Upload to GitHub Releases
        run: $SCRIPTS_DIR/step-6_upload_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
