name: Check Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  x86_64-linux-gnu-gcc_15_2_0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libc_version: [
          "2.28", "2.29", "2.30", "2.31", "2.32", "2.33", "2.34", 
          "2.35", "2.36", "2.37", "2.38", "2.39", "2.40", "2.41", "2.42"
        ]
      fail-fast: false  # Continue running other matrix jobs even if one fails

    name: Check Build for gcc 15.2.0 glibc ${{ matrix.libc_version }} on x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build with LIBC ${{ matrix.libc_version }}
        run: |
          ./bazel build \
            --repo_env=toolchains_cc_target=x86_64-linux-gnu \
            --repo_env=toolchains_cc_libc_version=${{ matrix.libc_version }} \
            --repo_env=toolchains_cc_compiler_version=15.2.0 \
            //...

  x86_64-linux-musl-gcc_15_2_0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libc_version: [
          "1.2.5",
        ]
      fail-fast: false  # Continue running other matrix jobs even if one fails

    name: Check Build for gcc 15.2.0 musl ${{ matrix.libc_version }} on x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build with LIBC ${{ matrix.libc_version }}
        run: |
          ./bazel build \
            --repo_env=toolchains_cc_target=x86_64-linux-musl \
            --repo_env=toolchains_cc_libc_version=${{ matrix.libc_version }} \
            --repo_env=toolchains_cc_compiler_version=15.2.0 \
            //...

  x86_64-linux-gnu-gcc_14_3_0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libc_version: [
          "2.28", "2.29", "2.30", "2.31", "2.32", "2.33", "2.34", 
          "2.35", "2.36", "2.37", "2.38", "2.39", "2.40", "2.41", "2.42"
        ]
      fail-fast: false  # Continue running other matrix jobs even if one fails

    name: Check Build for gcc 14.3.0 glibc ${{ matrix.libc_version }} on x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build with LIBC ${{ matrix.libc_version }}
        run: |
          ./bazel build \
            --repo_env=toolchains_cc_target=x86_64-linux-gnu \
            --repo_env=toolchains_cc_libc_version=${{ matrix.libc_version }} \
            --repo_env=toolchains_cc_compiler_version=14.3.0 \
            //...

  all-matrix-builds:
    runs-on: ubuntu-latest
    name: All matrix builds passed
    needs: [x86_64-linux-gnu-gcc_14_3_0, x86_64-linux-gnu-gcc_15_2_0, x86_64-linux-musl-gcc_15_2_0]
    if: always()
    
    steps:
      - name: Check matrix job results
        run: |
          if [[ "${{ needs.x86_64-linux-gnu-gcc_14_3_0.result }}" != "success" || "${{ needs.x86_64-linux-gnu-gcc_15_2_0.result }}" != "success" || "${{ needs.x86_64-linux-musl-gcc_15_2_0.result }}" != "success" ]]; then
            exit 1
          fi

  buildifier:
    runs-on: ubuntu-latest
    name: Run buildifier

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run buildifier
        run: |
          ./bazel run //private:buildifier.check

  commitlint:
    runs-on: ubuntu-latest
    name: Run commitlint
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Install commitlint
        run: npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Run commitlint
        run: |
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.sha }} --verbose
